# Generated by Django 5.1 on 2025-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('preço', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Preço')),
                ('qtd', models.PositiveIntegerField(default=0, null=True, verbose_name='Quantidade')),
            ],
        ),
    ]
